name: containers-ci
on:
  push:
    branches: [ main ]
    paths:
      - 'contrib/containers/**'
      - '.github/workflows/containers-ci.yml'
  pull_request:
    paths:
      - 'contrib/containers/**'
env:
  SHAI_REF: HEAD~1
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run container tests (no network needed)
        run: bash contrib/containers/tests/test_build_and_run.sh
