name: containers-ci

on:
  push:
    branches: [ main ]
    paths:
      - 'contrib/containers/**'
      - '.github/workflows/containers-ci.yml'
  pull_request:
    paths:
      - 'contrib/containers/**'

# Forcer la ref buildée pour éviter "1/merge" sur les PR
env:
  SHAI_REF: main        # on build 'main' d'ovh/shai pour les PR
  CARGO_LOCKED: 0       # pas de --locked hors tag

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run container tests (no network needed)
        run: bash contrib/containers/tests/test_build_and_run.sh
